/*
 * =====================================================================================
 *
 *       Filename:  debug.c
 *
 *    Description:  
 *
 *        Version:  1.0
 *        Created:  06/01/09 17:41:12
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  Luis Marcilio Braga de Oliveira (), lmbraga@embratel.com.br
 *        Company:  EMBRATEL S.A.
 *
 * =====================================================================================
 */
#include "debug.h"

#ifdef DEBUG
const char *event_descriptions[0x21] = 
{
    "",
    "HCI_INQUIRY_COMPLETE_EVENT", 
    "HCI_INQUIRY_RESULT_EVENT", 
    "HCI_CONNECTION_COMPLETE_EVENT", 
    "HCI_CONNECTION_REQUEST_EVENT", 
    "HCI_DISCONNECTION_COMPLETE_EVENT", 
    "HCI_AUTHENTICATION_COMPLETE_EVENT", 
    "HCI_REMOTE_NAME_REQUEST_COMPLETE_EVENT", 
    "HCI_ENCRYPTION_CHANGE_EVENT", 
    "HCI_CHANGE_CONNECTION_LINK_KEY_COMPLETE_EVENT", 
    "HCI_MASTER_LINK_KEY_COMPLETE_EVENT", 
    "HCI_READ_REMOTE_SUPPORTED_FEATURES_COMPLETE_EVENT", 
    "HCI_READ_REMOTE_VERSION_COMPLETE_EVENT", 
    "HCI_Q0S_SETUP_COMPLETE_EVENT", 
    "HCI_COMMAND_COMPLETE_EVENT", 
    "HCI_COMMAND_STATUS_EVENT", 
    "HCI_HARDWARE_ERROR_EVENT", 
    "HCI_FLUSH_OCCURED_EVENT", 
    "HCI_ROLE_CHANGE_EVENT", 
    "HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT", 
    "HCI_MODE_CHANGE_EVENT", 
    "HCI_RETURN_LINK_KEYS_EVENT", 
    "HCI_PIN_CODE_REQUEST_EVENT", 
    "HCI_LINK_KEY_REQUEST_EVENT", 
    "HCI_LINK_KEY_NOTIFICATION_EVENT", 
    "HCI_LOOPBACK_COMMAND_EVENT", 
    "HCI_DATA_BUFFER_OVERFLOW_EVENT", 
    "HCI_MAX_SLOTS_CHANGE_EVENT", 
    "HCI_READ_CLOCK_OFFSET_COMPLETE_EVENT", 
    "HCI_CONNECTION_PACKET_TYPE_CHANGED_EVENT", 
    "HCI_QOS_VIOLATION_EVENT", 
    "HCI_PAGE_SCAN_MODE_CHANGE_EVENT", 
    "HCI_PAGE_SCAN_REPETITION_MODE_CHANGE_EVENT" 
};



/* hci error codes */

char *error_descriptions[0x29] = 
{
    "HCI_UNKNOWN_HCI_COMMAND", 
    "HCI_NO_CONNECTION", 
    "HCI_HARDWARE_FAILURE", 
    "HCI_PAGE_TIMEOUT", 
    "HCI_AUTHENTICATION_FAILURE", 
    "HCI_KEY_MISSING", 
    "HCI_MEMORY_FULL", 
    "HCI_CONNECTION_TIMEOUT", 
    "HCI_MAX_NUMBER_OF_CONNECTIONS", 
    "HCI_MAX_NUMBER_OF_SCO_CONNECTIONS_TO_A_DEVICE", 
    "HCI_ACL_CONNECTION_ALREADY_EXISTS", 
    "HCI_COMMAND_DISALLOWED", 
    "HCI_HOST_REJECTED_DUE_TO_LIMITED_RESOURCES", 
    "HCI_HOST_REJECTED_DUE_TO_SECURITY_REASONS", 
    "HCI_HOST_REJECTED_DUE_TO_A_REMOTE_DEVICE_ONLY_A_PERSONAL_DEVICE", 
    "HCI_HOST_TIMEOUT", 
    "HCI_UNSUPPORTED_FEATURE_OR_PARAMETER_VALUE", 
    "HCI_INVALID_HCI_COMMAND_PARAMETERS", 
    "HCI_OTHER_END_TERMINATED_CONNECTION_USER_ENDED_CONNECTION", 
    "HCI_OTHER_END_TERMINATED_CONNECTION_LOW_RESOURCES", 
    "HCI_OTHER_END_TERMINATED_CONNECTION_ABOUT_TO_POWER_OFF", 
    "HCI_CONNECTION_TERMINATED_BY_LOCAL_HOST", 
    "HCI_REPEATED_ATTEMPTS", 
    "HCI_PAIRING_NOT_ALLOWED", 
    "HCI_UNKNOWN_LMP_PDU", 
    "HCI_UNSUPPORTED_REMOTE_FEATURE", 
    "HCI_SCO_OFFSET_REJECTED", 
    "HCI_SCO_INTERVAL_REJECTED", 
    "HCI_SCO_AIR_MODE_REJECTED", 
    "HCI_INVALID_LMP_PARAMETERS", 
    "HCI_UNSPECIFIED_ERROR", 
    "HCI_UNSUPPORTED_LMP_PARAMETER", 
    "HCI_ROLE_CHANGE_NOT_ALLOWED", 
    "HCI_LMP_RESPONSE_TIMEOUT", 
    "HCI_LMP_ERROR_TRANSACTION_COLLISION", 
    "HCI_LMP_PDU_NOT_ALLOWED", 
    "HCI_ENCRYPTION_MODE_NOT_ACCEPTABLE", 
    "HCI_UNIT_KEY_USED", 
    "HCI_QOS_NOT_SUPPORTED", 
    "HCI_INSTANT_PASSED", 
    "HCI_PAIRING_WITH_UNIT_KEY_NOT_SUPPORTED" 
};

/* l2cap command codes */

char *l2cap_command_codes[0x0C] = 
{
    "L2CAP_RESERVED"
    ,"L2CAP_COMMAND_REJECT"
    ,"L2CAP_CONNECTION_REQUEST"
    ,"L2CAP_CONNECTION_RESPONSE"
    ,"L2CAP_CONFIGURE_REQUEST"
    ,"L2CAP_CONFIGURE_RESPONSE"
    ,"L2CAP_DISCONNECTION_REQUEST"
    ,"L2CAP_DISCONNECTION_RESPONSE"
    ,"L2CAP_ECHO_REQUEST"
    ,"L2CAP_ECHO_RESPONSE"
    ,"L2CAP_INFORMATION_REQUEST"
    ,"L2CAP_INFORMATION_RESPONSE"
};


#endif

